eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9000/eureka}
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:    
  h2:
    console:
      enabled: true
